// Helper to format Date / ISO string / Timestamp to standard Vietnam Local Time (HH:mm:ss dd/MM/yyyy)
export function formatDateTime(dateStr?: string | number | any): string {
  if (!dateStr) return '-';
  try {
    // 1. Handle Jackson array format: [yyyy, mm, dd, hh, mm, ss]
    if (Array.isArray(dateStr)) {
      const [y, m, d, hh, mm, ss] = dateStr;
      const pad = (n: number) => (n < 10 ? '0' + n : String(n));
      return `${pad(hh || 0)}:${pad(mm || 0)}:${pad(ss || 0)} ${pad(d || 1)}/${pad(m || 1)}/${y}`;
    }

    const str = String(dateStr).trim();

    // 2. Handle ISO date string without timezone offset (e.g. "2026-08-22T07:33:53" or "2026-08-22 07:33:53")
    // This directly preserves the Vietnam Local Time generated by the backend without timezone distortion
    const match = str.match(/^(\d{4})[-/](\d{1,2})[-/](\d{1,2})[T\s](\d{1,2}):(\d{1,2})(?::(\d{1,2}))?/);
    if (match && !str.endsWith('Z') && !str.includes('+') && !str.includes('-0')) {
      const [, year, month, day, hour, minute, second] = match;
      const pad = (n: string | number) => {
        const num = Number(n || 0);
        return num < 10 ? '0' + num : String(num);
      };
      return `${pad(hour)}:${pad(minute)}:${pad(second)} ${pad(day)}/${pad(month)}/${year}`;
    }

    // 3. Fallback for timestamps in ms or UTC ISO strings ending in 'Z'
    const d = new Date(dateStr);
    if (isNaN(d.getTime())) return str;

    return d.toLocaleString('vi-VN', {
      timeZone: 'Asia/Ho_Chi_Minh',
      hour: '2-digit',
      minute: '2-digit',
      second: '2-digit',
      day: '2-digit',
      month: '2-digit',
      year: 'numeric',
      hour12: false
    });
  } catch (e) {
    return String(dateStr);
  }
}
